# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "frontcoded.com"
description: > # this means to ignore newlines until "email:"
   A dumping ground for web development stuff

email: hello@tomraithel.de
#blog logo
logo: "/assets/images/frontcoded-logo.png"
# blog cover
cover: "/assets/images/cover.png"

name: 'Tom Raithel'
author: 'Tom Raithel'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://frontcoded.com" # the base hostname & protocol for your site
baseurl: ""

permalink: /:title.html

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/tomraithel
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/tomraithel
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
